services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: bigabbo
      POSTGRES_PASSWORD: bigabbo
      POSTGRES_DB: circuitry
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
